### ISSUE TITLE
Python version not working

### ISSUE THREAD

**Issue by ziemann-engineering** [mayhem/smi_leds#1]
Hi,

thanks for making the SMI led thing a bit more accessible. Your C version works for me, on a Zero 2 with recent 32 bit Pi os lite. The python version however does not do anything, not error either. I figured maybe the platform dependent setup (frequency and memory address) is wrong, but I am not familiar with python software distribution, and I was unable to figure out if the platform is detected and set correctly. 

Any idea where to look for the issue?

Best regards,
Thomas

**Comment by mayhem** [comment]
Hi!

Lets see if we can get this working! Could you please create a new virtual env, run the python setup and then paste the whole output of the setup here so I can look at it? FWIW, I had tested this code with on a zero 2, so it should work...

**Comment by ziemann-engineering** [comment]
Hi. The normal pip install has little output, none of it interesting, and it seems it does not by default create a log. So, in a new venv, I installed wheel first (to avoid a mountain of messages related to that) and then ran pip with -vvv, but I still see nothing interesting. Was this what you meant by "output of the setup"?

```
ze@raspberrypi:~ $ ~/testenv3/bin/pip -vvv install smileds
Using pip 23.0.1 from /home/ze/testenv3/lib/python3.11/site-packages/pip (python 3.11)
Non-user install because user site-packages disabled
Created temporary directory: /tmp/pip-build-tracker-4vi9908t
Initialized build tracking at /tmp/pip-build-tracker-4vi9908t
Created build tracker: /tmp/pip-build-tracker-4vi9908t
Entered build tracker: /tmp/pip-build-tracker-4vi9908t
Created temporary directory: /tmp/pip-install-qr0v05io
Created temporary directory: /tmp/pip-ephem-wheel-cache-2lsl3zey
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
2 location(s) to search for versions of smileds:
* https://pypi.org/simple/smileds/
* https://www.piwheels.org/simple/smileds/
Fetching project page and analyzing links: https://pypi.org/simple/smileds/
Getting page https://pypi.org/simple/smileds/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/smileds/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/smileds/ HTTP/1.1" 304 0
Fetched page https://pypi.org/simple/smileds/ as application/vnd.pypi.simple.v1+json
  Found link https://files.pythonhosted.org/packages/92/2b/16fbd7bd851d2210afd8e6872f397c48bab29a90eec7a3904d3cdc56d5f1/smileds-2024.8.25.2.tar.gz (from https://pypi.org/simple/smileds/), version: 2024.8.25.2
  Found link https://files.pythonhosted.org/packages/15/74/835d8ce00a2b640aae4960b8c22250f4e2ab87820d6d0cc9ab95e06bbde0/smileds-2024.8.25.3.tar.gz (from https://pypi.org/simple/smileds/), version: 2024.8.25.3
Fetching project page and analyzing links: https://www.piwheels.org/simple/smileds/
Getting page https://www.piwheels.org/simple/smileds/
Found index url https://www.piwheels.org/simple
Looking up "https://www.piwheels.org/simple/smileds/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): www.piwheels.org:443
https://www.piwheels.org:443 "GET /simple/smileds/ HTTP/1.1" 200 285
Updating cache with response from "https://www.piwheels.org/simple/smileds/"
etag object cached for 1209600 seconds
Caching due to etag
Fetched page https://www.piwheels.org/simple/smileds/ as text/html
  Skipping link: none of the wheel's tags (cp311-cp311-linux_armv6l) are compatible (run pip debug --verbose to show compatible tags): https://www.piwheels.org/simple/smileds/smileds-2024.8.25.3-cp311-cp311-linux_armv6l.whl#sha256=4a97617c9df4438e0883ea1ab8ba8bb3061cfe76fcc88990c1aab7e7de45c2d0 (from https://www.piwheels.org/simple/smileds/)
  Found link https://www.piwheels.org/simple/smileds/smileds-2024.8.25.3-cp311-cp311-linux_armv7l.whl#sha256=4a97617c9df4438e0883ea1ab8ba8bb3061cfe76fcc88990c1aab7e7de45c2d0 (from https://www.piwheels.org/simple/smileds/), version: 2024.8.25.3
  Skipping link: none of the wheel's tags (cp311-cp311-linux_armv6l) are compatible (run pip debug --verbose to show compatible tags): https://www.piwheels.org/simple/smileds/smileds-2024.8.25.2-cp311-cp311-linux_armv6l.whl#sha256=8aefa0529f3b4ab8f51e28f826f1c5408aad1f359fed522f3272998df3fd9512 (from https://www.piwheels.org/simple/smileds/)
  Found link https://www.piwheels.org/simple/smileds/smileds-2024.8.25.2-cp311-cp311-linux_armv7l.whl#sha256=8aefa0529f3b4ab8f51e28f826f1c5408aad1f359fed522f3272998df3fd9512 (from https://www.piwheels.org/simple/smileds/), version: 2024.8.25.2
Skipping link: not a file: https://www.piwheels.org/simple/smileds/
Skipping link: not a file: https://pypi.org/simple/smileds/
Given no hashes to check 4 links for project 'smileds': discarding no candidates
Collecting smileds
  Created temporary directory: /tmp/pip-unpack-xjmojpdf
  Found index url https://www.piwheels.org/simple
  Looking up "https://www.piwheels.org/simple/smileds/smileds-2024.8.25.3-cp311-cp311-linux_armv7l.whl" in the cache
  Current age based on date: 227
  https://www.piwheels.org:443 "GET /simple/smileds/smileds-2024.8.25.3-cp311-cp311-linux_armv7l.whl HTTP/1.1" 304 0
  Using cached https://www.piwheels.org/simple/smileds/smileds-2024.8.25.3-cp311-cp311-linux_armv7l.whl (36 kB)
  Added smileds from https://www.piwheels.org/simple/smileds/smileds-2024.8.25.3-cp311-cp311-linux_armv7l.whl#sha256=4a97617c9df4438e0883ea1ab8ba8bb3061cfe76fcc88990c1aab7e7de45c2d0 to build tracker '/tmp/pip-build-tracker-4vi9908t'
  Removed smileds from https://www.piwheels.org/simple/smileds/smileds-2024.8.25.3-cp311-cp311-linux_armv7l.whl#sha256=4a97617c9df4438e0883ea1ab8ba8bb3061cfe76fcc88990c1aab7e7de45c2d0 from build tracker '/tmp/pip-build-tracker-4vi9908t'
Requirement already satisfied: wheel in ./testenv3/lib/python3.11/site-packages (from smileds) (0.45.1)
Created temporary directory: /tmp/pip-unpack-nw_utpxi
Installing collected packages: smileds

Successfully installed smileds-2024.8.25.3
Removed build tracker: '/tmp/pip-build-tracker-4vi9908t'
```

**Comment by mayhem** [comment]
Indeed, that doesn't provide a lot of info. Let me see about checking where in the python setup we can find the configured values for the RPI zero 2 and see if they are correct.

**Comment by ziemann-engineering** [comment]
I looked in several places, but could not find that info anywhere. It seemed to me it might just be compiled into the library and that's it, and I do not want to hunt for it in there. I also wasn't able to get a correct .so built in a reasonable time. Can you send me a .so for the zero 2 so I can test it? If that works it's definitely the distribution.

**Comment by mayhem** [comment]
Let me try that this weekend, but my time is limited, so I may not get to that this weekend.

**Comment by mayhem** [comment]
HI! I should have time today to test this/get you the .so. What distro do you use? I think I will install that and try it myself.

**Comment by ziemann-engineering** [comment]
Thank you. I used Pi os lite.
If you have any hints for me what to do or check please let me know, I don't want to take too much of your time.
I tried to build an .so for a bit, and also played around with the setup.py but did not get anywhere.

**Comment by mayhem** [comment]
I installed the latest version of Rpi OS and I am struggling with getting the sound system to not load. How did you do it?

**Comment by mayhem** [comment]
It does look like a distro problem of sorts -- no matter what I do on the more recent release of Rpi OS, I get a bus error when I run the C code. It works fine (C and python) on an older version of bullseye. Odd. I'm curious how you configured your PI 2 so that the C code runs.

**Comment by ziemann-engineering** [comment]
Nothing special, I think. Did you select 64 bit? Although the code is supposed to work with 64, the "original" and my setup are 32.

Other than that, I have this at the start of my bootloader config, simply not enabling audio or I2S. Below is nothing relevant, I think.

`
#Uncomment some or all of these to enable the optional hardware interfaces
dtparam=i2c_arm=on
#dtparam=i2s=on
dtparam=spi=on

#Enable audio (loads snd_bcm2835)
#dtparam=audio=on
`

**Comment by mayhem** [comment]
Ahhhh, that's it. It doesn't seem to work on 64 bit at all, but fine on 32 bit. Now that I know that I can start to find a solution. And yes, on 32 bit the python module does not work. Now that I can reproduce the problem, I'll start working on a fix!

**Comment by ziemann-engineering** [comment]
That's a step forward. Interesting that the newer Pi os broke Python, but not C. And some address/pointer is still stuck at 32 bit I guess?

**Comment by mayhem** [comment]
Ha, I found the problem. the example program exits before all the data transfer commands are complete. Adding a simple sleep(1) fixes the problem, lol. I'll improve the example program and add more docs about it only working on 32 bit, then I will do a release.

**Comment by mayhem** [comment]
Fixed, new release 2024.12.18.0 is now available.

**Comment by ziemann-engineering** [comment]
As far as I can see you changed only the code snippet in the readme, right? I was using the code under /examples, which runs continuously and had a sleep already. I also tried your new snippet now, same thing. Interestingly both examples never return and I cannot interrupt them, I have to kill it from another terminal. Must be something else going on with my setup :/

**Comment by mayhem** [comment]
Correct, no code changes. It worked fine for me on both the C and python version. And unless I can repeat your problem, there is no way for me to fix it. :(
